steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/git-developer-backend:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/git-developer-backend:latest
      - -f
      - Dockerfile.backend
      - .
    id: build-backend

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/git-developer-backend:$SHORT_SHA
    id: push-sha
    waitFor: [build-backend]

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/git-developer-backend:latest
    id: push-latest
    waitFor: [build-backend]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - git-developer-backend
      - --image=gcr.io/$PROJECT_ID/git-developer-backend:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8000
    waitFor: [push-sha]

images:
  - gcr.io/$PROJECT_ID/git-developer-backend:$SHORT_SHA
  - gcr.io/$PROJECT_ID/git-developer-backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
