repos:
- name: media_agent
  full_name: ramamurthy-540835/media_agent
  repo_url: https://github.com/ramamurthy-540835/media_agent
  description: Media Agent
  private: true
  updated_at: '2026-04-28T16:04:53Z'
  language: Python
- name: upgraded-computing-machine
  full_name: ramamurthy-540835/upgraded-computing-machine
  repo_url: https://github.com/ramamurthy-540835/upgraded-computing-machine
  description: Upgraded Computing Machine
  private: false
  updated_at: '2026-04-28T15:56:39Z'
  language: HTML
- name: ai_sql
  full_name: ramamurthy-540835/ai_sql
  repo_url: https://github.com/ramamurthy-540835/ai_sql
  description: Advanced system for converting English data quality rules into validated
    SQL using LangGraph, Chroma, and Neo4j
  private: false
  updated_at: '2026-04-28T15:55:42Z'
  language: HTML
- name: cement-ai
  full_name: ramamurthy-540835/cement-ai
  repo_url: https://github.com/ramamurthy-540835/cement-ai
  description: CementAI — GenAI Optimization for Cement Industry
  private: false
  updated_at: '2026-04-28T15:53:04Z'
  language: Python
- name: chennai-google
  full_name: ramamurthy-540835/chennai-google
  repo_url: https://github.com/ramamurthy-540835/chennai-google
  description: Chennai Google
  private: false
  updated_at: '2026-04-28T15:51:32Z'
  language: HTML
- name: ai-agent
  full_name: ramamurthy-540835/ai-agent
  repo_url: https://github.com/ramamurthy-540835/ai-agent
  description: agent-assist-pro
  private: false
  updated_at: '2026-04-28T15:49:36Z'
  language: JavaScript
- name: MeterReaderProExpo
  full_name: ramamurthy-540835/MeterReaderProExpo
  repo_url: https://github.com/ramamurthy-540835/MeterReaderProExpo
  description: Electricity Meter Reader Pro Expo
  private: false
  updated_at: '2026-04-28T15:42:05Z'
  language: JavaScript
- name: talentedge
  full_name: ramamurthy-540835/talentedge
  repo_url: https://github.com/ramamurthy-540835/talentedge
  description: Talentedge
  private: true
  updated_at: '2026-04-28T15:28:21Z'
  language: TypeScript
- name: costco-analytics
  full_name: ramamurthy-540835/costco-analytics
  repo_url: https://github.com/ramamurthy-540835/costco-analytics
  description: Costco Analytics
  private: false
  updated_at: '2026-04-28T15:25:37Z'
  language: Python
- name: chatbot
  full_name: ramamurthy-540835/chatbot
  repo_url: https://github.com/ramamurthy-540835/chatbot
  description: costco-chatbot
  private: true
  updated_at: '2026-04-28T15:23:45Z'
  language: JavaScript
- name: agent-orchestrator
  full_name: ramamurthy-540835/agent-orchestrator
  repo_url: https://github.com/ramamurthy-540835/agent-orchestrator
  description: Agent Orchestrator
  private: false
  updated_at: '2026-04-28T15:17:52Z'
  language: Python
- name: w3os
  full_name: ramamurthy-540835/w3os
  repo_url: https://github.com/ramamurthy-540835/w3os
  description: '- Comprehensive framework designed to simplify decentralized application
    (dApp) development.'
  private: false
  updated_at: '2026-04-28T15:11:49Z'
  language: TypeScript
- name: costco-agent-assist
  full_name: ramamurthy-540835/costco-agent-assist
  repo_url: https://github.com/ramamurthy-540835/costco-agent-assist
  description: Costco Agent Assist
  private: false
  updated_at: '2026-04-28T11:03:12Z'
  language: JavaScript
- name: bigquery-interactive-demos
  full_name: ramamurthy-540835/bigquery-interactive-demos
  repo_url: https://github.com/ramamurthy-540835/bigquery-interactive-demos
  description: Bigquery Interactive Demos
  private: true
  updated_at: '2026-04-28T10:08:50Z'
  language: HTML
- name: healthcare-vbc-pa
  full_name: ramamurthy-540835/healthcare-vbc-pa
  repo_url: https://github.com/ramamurthy-540835/healthcare-vbc-pa
  description: Healthcare Vbc Pa
  private: true
  updated_at: '2026-04-28T09:21:29Z'
  language: TypeScript
- name: finetuning
  full_name: ramamurthy-540835/finetuning
  repo_url: https://github.com/ramamurthy-540835/finetuning
  description: Fine tunning LLM
  private: false
  updated_at: '2026-04-28T09:18:27Z'
  language: Python
- name: sakthi-platform
  full_name: ramamurthy-540835/sakthi-platform
  repo_url: https://github.com/ramamurthy-540835/sakthi-platform
  description: The MCP Language (Sakthi) is a specialized framework for designing
    and executing Model Context Protocols (MCP) in Natural Language Processing. It
    provides a structured approach to manage context-aware workflows, semantic parsing,
    and integration with LLMs for context-driven decision-making and language transformations
  private: false
  updated_at: '2026-04-28T09:02:53Z'
  language: Python
- name: weathernext
  full_name: ramamurthy-540835/weathernext
  repo_url: https://github.com/ramamurthy-540835/weathernext
  description: Weathernext
  private: false
  updated_at: '2026-04-28T08:40:44Z'
  language: TypeScript
- name: prompt_craft2.0
  full_name: ramamurthy-540835/prompt_craft2.0
  repo_url: https://github.com/ramamurthy-540835/prompt_craft2.0
  description: Prompt Craft2.0
  private: false
  updated_at: '2026-04-28T08:09:03Z'
  language: TypeScript
- name: linkedin
  full_name: ramamurthy-540835/linkedin
  repo_url: https://github.com/ramamurthy-540835/linkedin
  description: Linkedin Generator
  private: false
  updated_at: '2026-04-28T07:59:18Z'
  language: ''
- name: hc-pa-vbc
  full_name: ramamurthy-540835/hc-pa-vbc
  repo_url: https://github.com/ramamurthy-540835/hc-pa-vbc
  description: ''
  private: false
  updated_at: '2026-04-18T10:56:37Z'
  language: ''
- name: healthcare_vbc_pa
  full_name: ramamurthy-540835/healthcare_vbc_pa
  repo_url: https://github.com/ramamurthy-540835/healthcare_vbc_pa
  description: ''
  private: true
  updated_at: '2026-04-10T12:08:16Z'
  language: ''
- name: mhh-data-ai-platform-differentiators
  full_name: mitaei/mhh-data-ai-platform-differentiators
  repo_url: https://github.com/mitaei/mhh-data-ai-platform-differentiators
  description: Request to Create Repository Structure for Data AI Platform Differentiators
  private: true
  updated_at: '2026-04-09T10:04:30Z'
  language: Python
- name: mhh_ai_knowledge_platform
  full_name: mitaei/mhh_ai_knowledge_platform
  repo_url: https://github.com/mitaei/mhh_ai_knowledge_platform
  description: '#10839'
  private: true
  updated_at: '2026-04-09T09:58:28Z'
  language: TypeScript
- name: mhh-adept-solution-prior-authorization
  full_name: mitaei/mhh-adept-solution-prior-authorization
  repo_url: https://github.com/mitaei/mhh-adept-solution-prior-authorization
  description: <div align="center">
  private: true
  updated_at: '2026-04-09T09:55:28Z'
  language: JavaScript
- name: mhh-ssis-to-pyspark
  full_name: mitaei/mhh-ssis-to-pyspark
  repo_url: https://github.com/mitaei/mhh-ssis-to-pyspark
  description: '# 9647'
  private: true
  updated_at: '2026-04-09T09:44:36Z'
  language: ''
- name: mhh_lnd_knowledge_platform
  full_name: mitaei/mhh_lnd_knowledge_platform
  repo_url: https://github.com/mitaei/mhh_lnd_knowledge_platform
  description: '#10839'
  private: true
  updated_at: '2026-04-09T09:44:32Z'
  language: ''
- name: mhh_ai_assessment_certification
  full_name: mitaei/mhh_ai_assessment_certification
  repo_url: https://github.com/mitaei/mhh_ai_assessment_certification
  description: '#10839'
  private: true
  updated_at: '2026-04-09T09:44:31Z'
  language: ''
- name: aios
  full_name: ramamurthy-540835/aios
  repo_url: https://github.com/ramamurthy-540835/aios
  description: AI OS
  private: false
  updated_at: '2026-04-06T07:17:14Z'
  language: ''
- name: w3
  full_name: ramamurthy-540835/w3
  repo_url: https://github.com/ramamurthy-540835/w3
  description: ''
  private: false
  updated_at: '2026-02-17T08:49:00Z'
  language: ''
- name: mhh-databricks-agents
  full_name: mitaei/mhh-databricks-agents
  repo_url: https://github.com/mitaei/mhh-databricks-agents
  description: '#9127'
  private: true
  updated_at: '2026-02-10T13:24:59Z'
  language: Python
- name: mhh-adept-modernizer
  full_name: mitaei/mhh-adept-modernizer
  repo_url: https://github.com/mitaei/mhh-adept-modernizer
  description: '# 9993'
  private: true
  updated_at: '2026-01-30T20:24:26Z'
  language: TypeScript
- name: mhh-sas-to-pyspark
  full_name: mitaei/mhh-sas-to-pyspark
  repo_url: https://github.com/mitaei/mhh-sas-to-pyspark
  description: '# 9647'
  private: true
  updated_at: '2026-01-13T05:45:58Z'
  language: Python
- name: mhh-informatica-to-pyspark
  full_name: mitaei/mhh-informatica-to-pyspark
  repo_url: https://github.com/mitaei/mhh-informatica-to-pyspark
  description: '# 9647'
  private: true
  updated_at: '2026-01-07T13:56:47Z'
  language: ''
- name: jhp-adept
  full_name: ramamurthy-540835/jhp-adept
  repo_url: https://github.com/ramamurthy-540835/jhp-adept
  description: JHP Code Conversion ADEPT
  private: false
  updated_at: '2026-01-02T03:50:08Z'
  language: TypeScript
- name: csat
  full_name: ramamurthy-540835/csat
  repo_url: https://github.com/ramamurthy-540835/csat
  description: ''
  private: false
  updated_at: '2025-12-09T05:23:22Z'
  language: ''
- name: sokosumi-agents
  full_name: ramamurthy-540835/sokosumi-agents
  repo_url: https://github.com/ramamurthy-540835/sokosumi-agents
  description: Cardano Life Agents v2.0
  private: false
  updated_at: '2025-11-30T01:16:48Z'
  language: TypeScript
- name: cardano-life-agents-v31
  full_name: ramamurthy-540835/cardano-life-agents-v31
  repo_url: https://github.com/ramamurthy-540835/cardano-life-agents-v31
  description: '"# cardano-life-agents-v31"'
  private: false
  updated_at: '2025-11-29T11:20:45Z'
  language: TypeScript
- name: cardano-life-agents-v2
  full_name: ramamurthy-540835/cardano-life-agents-v2
  repo_url: https://github.com/ramamurthy-540835/cardano-life-agents-v2
  description: Cardano Life Agents v2.0
  private: true
  updated_at: '2025-11-29T11:17:04Z'
  language: TypeScript
- name: cardano-life-agents
  full_name: ramamurthy-540835/cardano-life-agents
  repo_url: https://github.com/ramamurthy-540835/cardano-life-agents
  description: Cardano Life Agents
  private: true
  updated_at: '2025-11-26T04:06:14Z'
  language: TypeScript
- name: Splunk_GCP
  full_name: mitchatboat/Splunk_GCP
  repo_url: https://github.com/mitchatboat/Splunk_GCP
  description: 'Splunk to GCP '
  private: false
  updated_at: '2025-11-11T11:32:41Z'
  language: JavaScript
- name: ai-tutor
  full_name: ramamurthy-540835/ai-tutor
  repo_url: https://github.com/ramamurthy-540835/ai-tutor
  description: AI-powered educational platform with Next.js, Firestore, and Vertex
    AI
  private: false
  updated_at: '2025-11-08T18:19:37Z'
  language: JavaScript
- name: cementai-optimizer
  full_name: ramamurthy-540835/cementai-optimizer
  repo_url: https://github.com/ramamurthy-540835/cementai-optimizer
  description: cementai-optimizer
  private: false
  updated_at: '2025-11-02T15:09:34Z'
  language: TypeScript
