import { NextResponse } from 'next/server';

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const name = searchParams.get('name');

  // Mock transcript data based on the app name
  const mockTranscripts = {
    vbc_dashboard: "This is a mock transcript for the Value Based Care dashboard. It explains how to use risk stratification and care insights to improve patient outcomes. The system provides real-time data analysis to identify high-risk patients and recommend personalized care plans. It also tracks key performance indicators for overall population health management.",
    weathernext_dashboard: "Mock transcript for WeatherNext AI Intelligence. This platform uses advanced AI models to provide accurate weather forecasting and climate intelligence. It features a 3D globe with auto-rotate functionality, alert scans for danger and warning levels, and detailed forecasts for various cities. Users can export data and talk to the Weather AI for insights.",
    adept_healthcare: "This is a mock transcript for the Adept Healthcare platform. It focuses on prior authorization and value-based care. The system offers a critical risk network view, population intel, and AI-predicted risk trends. It also provides AI recommendations for clinical operations, physicians, care managers, and finance directors. The platform is powered by BigQuery, Gemini, and GCP.",
    dataeng_console: "Mock transcript for the Data Engineering Console. This console is designed for managing data engineering pipelines and analytics. It provides tools for data ingestion, transformation, and storage. Users can monitor pipeline health, perform ad-hoc queries, and visualize data flows. The console integrates with various data sources and destinations.",
    ctopteam_frontend: "This is a mock transcript for the GenAI + Modernization Platform UI. It showcases the capabilities of generative AI and modernization tools. The platform allows users to interact with AI models, generate content, and manage modernized applications. It features a user-friendly interface for various AI-driven tasks and integrates with cloud services.",
  };

  const transcript = mockTranscripts[name] || `Default mock transcript for application: ${name}. This is a placeholder for content that would be generated by a backend service.`;

  return NextResponse.json({ name, transcript });
}
